### ISSUE TITLE
Missing LICENSE file

### ISSUE THREAD

**Issue by mbeckem** [jlguenego/asn.1#1]
Hi,

during a routine license check my team noticed that your package does not provide a license file, although it declares `ISC` in its `package.json`.
By my understanding people cannot use the package as-is, e.g. when including as a dependency via node-expose-sspi.

Perhaps you could simply add a file similar to https://github.com/jlguenego/node-expose-sspi/blob/master/LICENSE.

Thanks!

**Comment by jlguenego** [comment]
Ok, I do it.
